name: daxos 

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bokeh
  - cupy=13.3.0 
  - dask=2023.1.1
  - dask-core=2023.1.1
  - dask-cuda=23.2.1
  - dask-jobqueue=0.8.1
  - distributed=2023.1.1
  - h5py
  - hdf5
  - matplotlib
  - numpy
  - pandas
  - patsy
  - pillow
  - pip=22.3.1
  - python=3.10
  - scikit-learn
  - scipy
  - snakemake
  - six
  - statsmodels
  - zarr
  - pytables
  - xgboost=1.7.6
  - pip:
      - ipython
      - memory_profiler
      - py3nvml 
      - pytest
      - tqdm
