#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=10:00:00
#SBATCH --job-name=dask-root
#SBATCH --mem=30GB
#SBATCH --signal=B:SIGUSR1@120
#SBATCH --mail-type=end
#SBATCH --mail-type=fail
#SBATCH --mail-type=begin
#SBATCH --output=job.%j.log
#SBATCH --error=job.%j.err

default-resources:
    runtime: 30 # minutes
    mem_mb_per_cpu: 40000 # Mb
    cpus_per_task: 1
    tasks: 1
    slurm_account: "eadbwp2"
    slurm_partition: "t1b"

set-resources:
    convert_raw_to_hdf5:
        runtime: 360 # minutes
        mem_mb_per_cpu: 80000 # Mb
        cpus_per_task: 1
        tasks: 1
        slurm_account: "eadbwp2"
        slurm_partition: "'24c4'" # queues like 24c must be as "'24c'" with nested quotes 